### ISSUE TITLE
@ApplicationModuleTest does not work in subclass

### ISSUE THREAD

**Issue by michaldo** [spring-projects-experimental/spring-modulith#176] opened 2023-03-30 17:44 UTC
Hi, example:
```
// @SpringBootTest  -- it works
@ApplicationModuleTest abstract class MyBaseTest {}

class MyConcreteTest extends MyBaseTest {

    @Test
    void contextLoads() {
    }
}
```
> Starting MyConcreteTest 
> A component required a bean of type 'org.springframework.modulith.test.ModuleTestExecution' that could not be found.

**Comment by odrotbohm** [comment] 2023-03-31 08:13
This sounds like a duplicate of #173 . Would you mind trying the 0.6 snapshots?

**Comment by midovlvn** [comment] 2023-03-31 09:56
Fixed in 0.6.0-SNAPSHOT

**Comment by odrotbohm** [comment] 2023-03-31 10:10
Awesome, happy coding! 🙃

**Closed by odrotbohm** 2023-03-31 10:10 UTC
Labels: in: test support, meta: waiting for feedback
